version: "3.9"
services:
  frontend:
    image: "node:16.14.0"
    working_dir: "/censys-app/frontend"
    # volumes:
    #   - ./frontend:/censys-app/frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: geo-locater-api_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  backend:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/geo-locater-api
    ports:
      - "3000:3000"
    depends_on:
      - db
